### ISSUE TITLE
Feature: User can see movies by category

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see movies by categories they choose.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can see now-playing movies on the carousel. They can also choose different categories by clicking on the tabs underneath the carousel. The default shows top-rated movies, and the user can see all of the corresponding movies by scrolling down.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feat 1 mob](https://user-images.githubusercontent.com/103100017/184028191-44050549-706c-45dc-b612-16c88c405b78.png)
![feat 1 desk](https://user-images.githubusercontent.com/103100017/184028089-2a45f382-ae57-4222-acef-d0723451fdc2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="home"]` to the HTML.
- [x] Create a carousel with placeholder images.
- [x] Ensure that the carousel looks nice on both mobile-sized and desktop-sized screens.
- [x] Remove the placeholder images.
- [x] Query the DOM for the carousel's image element.
- [x] Create a new `XMLHttpRequest()` object.
- [x] `open()` the `xhr` object to send a 'GET' request to 'https://developers.themoviedb.org/3/movies/now_playing'.
- [x] Set the `responseType`.
- [x] Listen for the 'load' event on the `xhr` object.
- [x] Log the status of the `xhr` object to the console.
- [x] Log the response of the `xhr` object to the console.
- [x] Loop through the response of the `xhr` object.
- [x] For each movie object in the response, concatenate its ''poster_image' property with 'https://image.tmdb.org/t/p/w500/'.
- [x] Set the result of the expression as the `src` attribute of the image element.
- [x] send() the request to begin loading the data from the server.
- [x] Add the carousel to the `div[data-view="home"]`.
- [x] Create four `<a>` elements as top-rated, trending, popular, and upcoming tabs.
- [x] Give each `<a>` elements a `data-view`.
- [x] Create a section for each `<a>` element using placeholder images.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for 'click' events on the category tabs to swap to the view that matches the tab value.
- [x] Add the section of categories to the `div[data-view="main"]`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
