### ISSUE TITLE
Bug: previous movie details

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#12]
#### Desired Behavior

The app should show a loader until the entire page is loaded.
The app should not show the previous movie detail when the user clicks to see a new movie detail.

#### Actual Behavior

An empty carousel is shown until 
The previous movie image and details show up for a split second.

#### Steps to Reproduce

To trigger the bug, a user must click on a movie to see its detail, then click on another movie to see the new detail.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] call the `viewSwap()` inside the `getDetails()`
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
