### ISSUE TITLE
Feature: User can see movie detail

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the details of each movie.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the poster image of the movie, the user can see the movie title, image, summary, release date, production company, and genre.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feat 2 mob](https://user-images.githubusercontent.com/103100017/184027991-05c01ede-b38e-4cd6-a1d1-5db6b4c95690.png)
![feat 2 desk](https://user-images.githubusercontent.com/103100017/184027995-1de9a378-e614-4254-a91f-e380ec7e7072.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="detail"]` to the HTML.
- [x] Create a dummy detail view and style it to match the wireframe.
- [x] Listen for 'click' events on all movie poster images.
- [x] Show the movie details view if a poster image was clicked.
- [x] Check that the detail view looks good on both mobile and desktop screens.
- [x] Remove the placeholder movie details.
- [x] Set an `id` attribute on all poster image dynamically created by constructor functions.
- [x] Create a new `xhr` object.
- [x] Make a request for movie detail using the movie ID set as the image `id` attribute.
- [x] Change the text content of the movie detail view by using the response data.
- [x] Listen for 'click' events on the logo.
- [x] Show the home view if the logo was clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
