### ISSUE TITLE
Feature: User can see the rating

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the rating of each movie.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see a star icon and an overall rating of the movie underneath each title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feat 3 mob](https://user-images.githubusercontent.com/103100017/184027640-500f3da5-28f6-45ab-b779-f99708f11f7b.png)
![feat 3 desk](https://user-images.githubusercontent.com/103100017/184027652-1a4a7f1a-a98e-45cb-8518-375c3a3fe834.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] get all the rating scores from the API by requesting for movie reviews
- [x] for each object in the array of results, add all the values of the rating property
- [x] find the average
- [x] dynamically render the average and a star icon
- [x] append it to the details page when the user clicks on a poster image
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
