### ISSUE TITLE
Feature: User can add the movie to their watchlist

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the movie to their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the add button under each movie, and see it inside their watchlist by clicking on the My List button on the nav area.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feat 4 mob](https://user-images.githubusercontent.com/103100017/184445551-c0cae884-5ca4-4a2b-b0c7-67d1fda76120.png)
![feat 4 mob 2](https://user-images.githubusercontent.com/103100017/184445557-0900c4f8-2286-44e5-8a24-1a06d266e1d4.png)
![feat 4 mob 3](https://user-images.githubusercontent.com/103100017/184445559-e449d8c4-5616-4d1e-a71f-cb3407e514fc.png)
![feat 4 desk](https://user-images.githubusercontent.com/103100017/184445563-6228184c-550b-43f7-bccc-262260812e23.png)
![feat 4 desk 2](https://user-images.githubusercontent.com/103100017/184445566-f9e2e599-3b89-4825-a075-d1ad0c03e337.png)
![feat 4 desk 3](https://user-images.githubusercontent.com/103100017/184445573-81779194-28e8-4b2d-93f9-13dc90a24d26.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] modify the `renderDetails` function to dynamically create an add button.
- [x] create a movie object with an id property and an image url property.
- [x] create a watchlist property on the data model.
- [x] listen for 'click' events on the add button to push the current movie object into the watchlist.
- [x] listen for 'click' events on the My List tab to swap to My List page.
- [x] dynamically create all the movies in the watchlist when the user clicks on My List tab.
- [x] clear the previously rendered My List.
- [x] reuse the `showDetails` function to show details if the user clicks the movie inside the My List page.
- [x] view swap to details page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
