### ISSUE TITLE
Feature: User can delete movies from their watchlist

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/AJAX-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete the movies inside their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can use the Remove from Watchlist button in the movie details view or use the Remove button in their watchlist to delete the movie from their watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feat 5 mob](https://user-images.githubusercontent.com/103100017/184446140-b3ba8deb-cf35-47f1-b891-edb01661a98f.png)
![feat 5 mob 2](https://user-images.githubusercontent.com/103100017/184446153-d87ebbd8-fd84-42cf-bded-70e3ec29a3a6.png)
![feat 5 desk](https://user-images.githubusercontent.com/103100017/184446165-37c7c0ba-2fd7-4cda-9ec9-958c172ac254.png)
![feat 5 desk 2](https://user-images.githubusercontent.com/103100017/184446171-95b565a2-ef26-48aa-949a-64cf52417088.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an event listener on the add button
- [x] when the user clicks the button, change the text content of the button to 'Remove'
- [x] check if the current detail page id is inside the watchlist data model array
- [x] if there is a match, do not push into the array
- [x] the current detail page is pushed into the watchlist data model array
- [x] when the user clicks again, the text changes back to 'Add to My List'
- [x] the current detail page is spliced from the watchlist data model array
- [x] whenever the detail page is rendered, check is the current detail page id has a match inside the watchlist data model array
- [x] if there is a match, set the text content of the button to 'Remove'
- [x] else, set the text content of the button to 'Add to My List'
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by williamstephen211** [comment]
많이 응원합니다.

**Comment by Scarlet-K** [comment]
> 많이 응원합니다.

감사합니다:)
